name: files-viewer
services:
  files:
    image: svenstaro/miniserve:latest
    container_name: pc_files
    restart: unless-stopped
    ports:
      - "8082:8080"
    volumes:
      - /root/paperclip-data:/data:ro
    command:
      - --port=8080
      - --interfaces=0.0.0.0
      - --auth=zkhchiche:fct-preview-2026
      - --title=fct deliverables
      - --enable-tar
      - --enable-zip
      - /data/fct-view
